# Puerto
server.port=8080

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_movify?connectTimeout=10
spring.datasource.username=movify_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Asegúrate de que esta sea la única línea de dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=movify-clave-secreta-2024
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://movify.ds2.eleueleo.com

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=movify2.app@gmail.com
spring.mail.password=wslp pczk qsvl dswr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL frontend
app.frontend.url=http://localhost:4200

# ARCHIVOS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# LOGGING - Ayuda a ver el error real de conexión y las consultas SQL
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE