# Puerto
server.port=8080

# Base de datos (producción)
spring.datasource.url=jdbc:postgresql://localhost:5432/movify_db?connectTimeout=10
spring.datasource.username=dev_movify
spring.datasource.password=Movify2026*
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=movify-clave-secreta-2024
app.jwt.expiration=86400000

# Código secreto de admin
app.admin.secret-code=MOVI-ADMIN-2024-SECRET

# CORS
app.cors.allowed-origins=http://localhost:4200,http://movify.ds2.eleueleo.com,https://movify.ds2.eleueleo.com

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=movify2.app@gmail.com
spring.mail.password=wslp pczk qsvl dswr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL frontend
app.frontend.url=http://movify.ds2.eleueleo.com

# ARCHIVOS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# LOGGING — producción (sin debug ni trace)
logging.level.root=WARN
logging.level.com.movify=INFO
logging.level.com.zaxxer.hikari=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.org.springframework.security=WARN
