# Puerto donde corre el backend
server.port=8080

# URL la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_movify
spring.datasource.username=movify_user
spring.datasource.password=123456

# Crea las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Clave secreta para los tokens JWT (minimo 32 caracteres)
app.jwt.secret=movify-desarrollo-software-universidad-valle-2024-proyecto-integrador
app.jwt.expiration=86400000

# Permite peticiones desde Angular
app.cors.allowed-origins=http://localhost:4200

# ── EMAIL GMAIL ────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=movify2.app@gmail.com
spring.mail.password=wslp pczk qsvl dswr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL del frontend para el enlace de recuperación
app.frontend.url=http://localhost:4200